### ISSUE TITLE
contacts that lack pgp

### ISSUE THREAD

**Issue by vv01f** [cryptomario/webmail-gpg#1]
I would like to give more incentive to users that do not have pgp yet.
for this a client side solution might generate keys for that specific contact and transfer the privatekey to the contact (e.g. on a second path, although having it with the mail itself would not make it less secure than the plaintext).
the idea behind is: force the contact to install a pgp solution on his side and make him generating his own keys for the next communication. in case of important information to the contact the incentive might be huge enough.
the concrete text of that first mail might also include a plaintext part giving advice how to install pgp and the encrypted part might furthermore give instructions on generating new keypairs. so the overall experience is kind of a quest to the contact.

**Comment by cryptomario** [comment]
I think this issue is out of scope for this project. Won't fix.
